- name: Create nginx directory
  ansible.builtin.file:
    path: "{{ root }}/nginx"
    state: directory
  tags:
    - stage
    - prod

- name: Copy nginx conf
  ansible.builtin.template:
    src: nginx.conf
    dest: "{{ root }}/nginx/nginx.conf"
  tags:
    - stage
    - prod

- name: Copy config.json
  ansible.builtin.template:
    src: "config.json"
    dest: "{{ root }}/client/build/config.json"
  tags:
    - stage
    - prod

- name: Copy build docker file to default file
  ansible.builtin.copy:
    src: "{{ root }}/docker-compose.build.yml"
    dest: "{{ root }}/docker-compose.yml"
    remote_src: yes
  tags:
    - dev

- name: Copy .env
  ansible.builtin.template:
    src: .env
    dest: "{{ root }}/.env"
    mode: 0600
  tags:
    - dev

- name: Copy docker compose cert
  ansible.builtin.template:
    src: docker-compose.cert.yml
    dest: "{{ root }}/docker-compose.cert.yml"
  tags:
    - stage
    - prod

- name: Copy docker compose
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ root }}/docker-compose.yml"
  tags:
    - stage
    - prod

- name: Copy certs.env
  ansible.builtin.template:
    src: certs.env
    dest: "{{ root }}/certs.env"
    mode: 0600
  tags:
    - stage
    - prod

- name: Copy secrets.env
  ansible.builtin.copy:
    src: secrets.env
    dest: "{{ root }}/secrets.env"
    mode: 0600
  tags:
    - stage
    - prod

- name: Ensure secrets directory exists
  ansible.builtin.file:
    path: "{{ root }}/secrets"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory
  tags:
    - stage
    - prod

- name: Copy digitalocean.ini
  ansible.builtin.template:
    src: digitalocean.ini
    dest: "{{ root }}/secrets/digitalocean.ini"
    mode: "0600"
  tags:
    - stage
    - prod

- name: Start Docker Compose cert containers
  community.docker.docker_compose_v2:
    project_src: "{{ root }}"
    files:
      - "{{ root }}/docker-compose.cert.yml"
    build: always
  tags:
    - stage
    - prod

- name: Start Docker Compose containers
  community.docker.docker_compose_v2:
    project_src: "{{ root }}"
    build: always
  environment:
    ENV: "{{ env }}"
  tags:
    - setup

- name: Add environment variable to user .bashrc
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export ENV="{{ env }}"'
    create: yes
  tags:
    - setup
