---
- name: Create DOCR Kubernetes secret
  shell: doctl registry kubernetes-manifest | kubectl apply -f -

- name: Login to registry
  shell: doctl registry login

- name: Tag images for DOCR
  shell: docker tag {{ item }}:{{ env }} {{ registry_name }}/{{ item }}:{{ env }}
  loop: "{{ registry_containers }}"

- name: Push images
  shell: docker push {{ registry_name }}/{{ item }}:{{ env }}
  loop: "{{ registry_containers }}"
