apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: football
  name: football
spec:
  replicas: 1
  selector:
    matchLabels:
      app: football
  template:
    metadata:
      labels:
        app: football
    spec:
      containers:
        - name: football
          image: "{{ registry_name }}/football:dev"
          ports:
            - containerPort: 3003
      imagePullSecrets:
        - name: registry-sports
