apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: football
  name: football
spec:
  replicas: 1
  selector:
    matchLabels:
      app: football
  template:
    metadata:
      labels:
        app: football
    spec:
      containers:
        - name: football
          image: "{{ registry_name }}/football:{{ env }}"
          env:
            - name: RAILS_ENV
              value: "production"
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails-secrets
                  key: secret_key_base
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: DATABASE_URL
            - name: REDIS_URL_SIDEKIQ
              valueFrom:
                secretKeyRef:
                  name: cache-url
                  key: CACHE_URL
          ports:
            - containerPort: 3003
      imagePullSecrets:
        - name: registry-sports
