apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
  labels:
    app: sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: "{{ registry_name }}/football:dev"
          command: ["bundle", "exec", "sidekiq"]
          env:
            - name: REDIS_URL_SIDEKIQ
              value: redis://redis:6379/1
            # - name: RAILS_ENV
            #   value: "production"
            # - name: RAILS_LOG_TO_STDOUT
            #   value: "true"
            # - name: SECRET_KEY_BASE
            #   valueFrom:
            #     secretKeyRef:
            #       name: rails-secrets
            #       key: secret_key_base
            # - name: DATABASE_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: database-url
            #       key: DATABASE_URL
      imagePullSecrets:
        - name: registry-sports
