# extra_vars.yml
repo_name: sports-app
infra_repo_name: sports-app-infra
services:
  - client
  - server
  - crawler

db_services:
  - auth
  - football

dependency_services:
  - db
  - redis

custom_services: "{{ services + db_services }}"
all_services: "{{ custom_services + dependency_services }}"
