# extra_vars.yml
repo_name: sports-app
infra_repo_name: sports-app-infra
services:
  - client
  - server
  - crawler

db_services:
  - auth
  - football

dependencies:
  - db
  - redis

custom_services: "{{ services + db_services }}"
all_services: "{{ custom_services + dependencies }}"
deployment_services: "{{ all_services + ['sidekiq'] }}"
