# extra_vars.yml
repo_name: sports-app
infra_repo_name: sports-app-infra
db_containers:
  - auth
  - football
registry_containers:
  - client
  - server
  - auth
  - football
  - crawler
service_containers:
  - client
  - server
  - auth
  - football
  - crawler
  - db
  - redis
deployment_containers:
  - client
  - server
  - auth
  - football
  - crawler
  - db
  - redis
  - sidekiq
