- name: Setup server
  hosts: all
  gather_facts: no
  roles:
    - setup_server
    - setup_docker
    - role: setup_ssh_config
      vars:
        server_name: "stage"

- name: Setup sports app
  hosts: all
  gather_facts: no
  become: yes
  become_user: "{{ user_name }}"
  vars:
    root: "~/{{ repo_name }}"
  roles:
    - setup_stage
