- name: Setup server
  hosts: all
  gather_facts: no
  roles:
    - setup_server
    - setup_docker
    - role: setup_ssh_config
      vars:
        server_name: "dev"
        env_var: "DEV_IP"

- name: Setup sports app
  hosts: all
  gather_facts: no
  become: yes
  become_user: "{{ user_name }}"
  roles:
    - setup_dev
    - database_cmd
